language: python

python: 3.6.6

branches: master

install:d
    - pip install mkdocs mkdocs-material pymdown-extensions pygments

before_deploy:
    - mkdocs build --verbose --clean --strict

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: docs
    on:
        branch: master
