site_name: 'DockerPlex Docs'
site_description: 'Documentation for complex plex setups using docker'
site_author: 'Edy'
site_url: 'https://docs.dockerplex.org'

docs_dir: mkdocs
site_dir: docs

nav:
  - Home: index.md
  - Docker:
    - Installing Docker: docker/docker.md
  - About: about.md

theme:
  name: 'material'
  #logo: 'images/logo.png'
  palette:
    primary: 'orange'
    accent: 'amber'
  feature:
    tabs: true

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - type: twitter
      link: https://twitter.com/EdyTheCow

google_analytics:
  - 'UA-121434074-2'
  - 'auto'
